### ISSUE TITLE
add error responses for users

### ISSUE THREAD

**Issue by jspeis** [hwchen/tesseract#107]
if a user query encounters an error would be good to return an error message

**Comment by hwchen** [comment]
Can you be more specific? 500 don't currently return a message (and probably won't, since it's a server error), but most 404 (related to missing drilldowns, etc) do. And the LL is designed to not error when possible.

**Comment by jspeis** [comment]
I think it would be nice if a 500-style error occurs in a "dev-mode" environment if the user could see the error message. Alternatively in a prod mode environment I think just a simple JSON response with some kind of high level error code could be helpful as well

**Comment by jspeis** [comment]
@hwchen IIRC this was added in can this be closed?

**Comment by hwchen** [comment]
This was added, so it can be closed.
