### ISSUE TITLE
annotations xml

### ISSUE THREAD

**Issue by hwchen** [hwchen/tesseract#81]
implement annotations for xml. It's done for json, but didn't want to mess with the xml yet. (it's a weird format, because it may have an `<Annotations>` tag around the `<Annotation>` tag, and most other lists, like `Dimension` and `Cube do not).

@MarcioPorto

**Comment by MarcioPorto** [comment]
@hwchen This was supposed to be closed by https://github.com/hwchen/tesseract/pull/89
