### ISSUE TITLE
[logic layer] basic api, one cube

### ISSUE THREAD

**Issue by hwchen** [hwchen/tesseract#83]
- cube
- drilldown
- measure (just one for now)
- time
arbitrary cuts
sort

**Comment by MarcioPorto** [comment]
- [ ] Optional cube param (not as part of the route)
- [ ] Arbitrary cuts
- [ ] Simplified drilldown names (`State` instead of `Geography.State`)
- [ ] Bracket notation support for drilldowns

**Comment by hwchen** [comment]
@MarcioPorto, @jspeis suggested making the cube param required at first; I think I would also tend that way. I suppose we'll probably have to discuss this again sometime though, after implementing v1 logic layer.

**Comment by MarcioPorto** [comment]
@hwchen My bad, I meant to say required there. I'll change it.

**Comment by hwchen** [comment]
no problem.

I also wanted to make a note about bracket notation support:

I think that when I do it for fully qualified names, I require brackets for each "section". I think that makes the logic easier for splitting. Are you planning on allowing mixed bracketed and un-bracketed names?

If so, would be curious about your strategy for parsing.

**Comment by MarcioPorto** [comment]
@hwchen I chose not to require brackets for each section. So it should work for either of these three options:

```
Pop,Geo
[Pop],Geo
[Pop],[Geo]
```
